//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Nhom1.Relationship_Table
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CH_QuanlyGiayDep : DbContext
    {
        public CH_QuanlyGiayDep()
            : base("name=CH_QuanlyGiayDep")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblChiTietHDDX> tblChiTietHDDX { get; set; }
        public virtual DbSet<tblChiTietHDNH> tblChiTietHDNH { get; set; }
        public virtual DbSet<tblHoaDonDX> tblHoaDonDX { get; set; }
        public virtual DbSet<tblHoaDonNH> tblHoaDonNH { get; set; }
        public virtual DbSet<tblKhachHang> tblKhachHang { get; set; }
        public virtual DbSet<tblNhanVien> tblNhanVien { get; set; }
        public virtual DbSet<tblSanPham> tblSanPham { get; set; }
        public virtual DbSet<tblXuong> tblXuong { get; set; }
    }
}
