//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Nhom1.Relationship_Table
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDDX
    {
        public string MaHDD { get; set; }
        public string MaSP { get; set; }
        public string Makhach { get; set; }
        public double Size { get; set; }
        public string Mausac { get; set; }
        public string Yeucaulam { get; set; }
        public double Dongia { get; set; }
        public Nullable<double> Giamgia { get; set; }
        public double Thanhtien { get; set; }
        public string Anh { get; set; }
        public string Ghichu { get; set; }
        public string DatraCH { get; set; }
    
        public virtual tblHoaDonDX tblHoaDonDX { get; set; }
        public virtual tblKhachHang tblKhachHang { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
