//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Nhom1.Relationship_Table
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChiTietHDNH
    {
        public string MaHDN { get; set; }
        public string MaSP { get; set; }
        public string Mausac { get; set; }
        public double Size { get; set; }
        public string Chatlieu { get; set; }
        public double TGBH { get; set; }
        public double SLban { get; set; }
        public string Anh { get; set; }
        public Nullable<double> Khuyenmai { get; set; }
        public double Thanhtien { get; set; }
        public string Ghichu { get; set; }
        public string Datrakhach { get; set; }
        public string Yeucaulam { get; set; }
    
        public virtual tblHoaDonNH tblHoaDonNH { get; set; }
        public virtual tblSanPham tblSanPham { get; set; }
    }
}
