//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Nhom1.Relationship_Table
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHoaDonDX
    {
        public string MaHDD { get; set; }
        public string Manhanvien { get; set; }
        public string Maxuong { get; set; }
        public System.DateTime Ngaydua { get; set; }
        public double Tongtien { get; set; }
    
        public virtual tblChiTietHDDX tblChiTietHDDX { get; set; }
        public virtual tblNhanVien tblNhanVien { get; set; }
        public virtual tblXuong tblXuong { get; set; }
    }
}
