//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Nhom1.Relationship_Table
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblNhanVien()
        {
            this.tblHoaDonDX = new HashSet<tblHoaDonDX>();
            this.tblHoaDonNH = new HashSet<tblHoaDonNH>();
        }
    
        public string Manhanvien { get; set; }
        public string Tennhanvien { get; set; }
        public string Gioitinh { get; set; }
        public System.DateTime Namsinh { get; set; }
        public string Diachi { get; set; }
        public string Anh { get; set; }
        public string Tencongviec { get; set; }
        public double Luong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHoaDonDX> tblHoaDonDX { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblHoaDonNH> tblHoaDonNH { get; set; }
    }
}
