//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChatlieu
    {
        public tblChatlieu()
        {
            this.tblHangs = new HashSet<tblHang>();
        }
    
        public string Machatlieu { get; set; }
        public string Tenchatlieu { get; set; }
    
        public virtual ICollection<tblHang> tblHangs { get; set; }
    }
}
