//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHDBan
    {
        public tblHDBan()
        {
            this.tblChitietHDBans = new HashSet<tblChitietHDBan>();
        }
    
        public string MaHDBan { get; set; }
        public string Manhanvien { get; set; }
        public System.DateTime Ngayban { get; set; }
        public string Makhach { get; set; }
        public double Tongtien { get; set; }
    
        public virtual ICollection<tblChitietHDBan> tblChitietHDBans { get; set; }
        public virtual tblKhach tblKhach { get; set; }
        public virtual tblNhanvien tblNhanvien { get; set; }
    }
}
