//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHang
    {
        public tblHang()
        {
            this.tblChitietHDBans = new HashSet<tblChitietHDBan>();
        }
    
        public string Mahang { get; set; }
        public string Tenhang { get; set; }
        public string Machatlieu { get; set; }
        public double Soluong { get; set; }
        public double Dongianhap { get; set; }
        public double Dongiaban { get; set; }
        public string Anh { get; set; }
        public string Ghichu { get; set; }
    
        public virtual tblChatlieu tblChatlieu { get; set; }
        public virtual ICollection<tblChitietHDBan> tblChitietHDBans { get; set; }
    }
}
