//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quanlybanhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblKhach
    {
        public tblKhach()
        {
            this.tblHDBans = new HashSet<tblHDBan>();
        }
    
        public string Makhach { get; set; }
        public string Tenkhach { get; set; }
        public string Diachi { get; set; }
        public string Dienthoai { get; set; }
    
        public virtual ICollection<tblHDBan> tblHDBans { get; set; }
    }
}
